### PR TITLE
Rectify image segmentation CSS issue

### PR DESCRIPTION
**Pull request by kavantan**
Might need your help to test this, if your docker works.

### CODE REVIEW

**Review by kangzongxian — COMMENTED** [review]
Seems to be not working on my side
imagesegmentation

**Comment by kangzongxian** [comment]
Doesn't really seem to work, this is the output I got
save image


save the image

**Comment by kavantan** [comment]
Wait idgi, is that not the expected output?

**Comment by kangzongxian** [comment]
LGTM!

**Review by kangzongxian — APPROVED** [review]

**Pull request merged**
